version: "3"
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=quizzard
      - PGHOST=db
      - PGPASSWORD=quizzardpass
      - PGDATABASE=quizzards
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    ports:
      - 35432:5432
    volumes:
      ##- "dbdata:/var/lib/postgresql/data"
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=quizzards
      - POSTGRES_USER=quizzard
      - POSTGRES_PASSWORD=quizzardpass
volumes:
  dbdata:
